title: Phillip Kesling
description: Staff-Level Data Engineer â€” Data Platforms, APIs, Analytics
# theme: jekyll-theme-minimal
# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
